# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(459, 302)
        Login.setStyleSheet("QDialog{\n"
"background-image: url(:/img06.png);\n"
"background-position: left 60%;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 14px;\n"
"    min-width:2em;\n"
"    color:white; /*字体颜色*/\n"
"    font-family:黑体;\n"
"    padding: 5px;\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(0, 150, 0);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #1E90FF; /*伪状态经过时背景色*/ \n"
"    border-style: inset;\n"
"}\n"
"QPushButton:!enabled{\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 200, 242, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget1 = QtWidgets.QWidget(Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 120, 338, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.horizontalLayout_2.addWidget(self.lineEdit_pwd)
        self.layoutWidget2 = QtWidgets.QWidget(Login)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 60, 338, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_user = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_user.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.horizontalLayout_3.addWidget(self.lineEdit_user)

        self.retranslateUi(Login)
        self.pushButton_2.clicked.connect(Login.close)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.pushButton.setText(_translate("Login", "登录"))
        self.pushButton_2.setText(_translate("Login", "退出"))
        self.label_2.setText(_translate("Login", "密码：  "))
        self.lineEdit_pwd.setText(_translate("Login", "123456"))
        self.label.setText(_translate("Login", "用户名："))
        self.lineEdit_user.setText(_translate("Login", "hao"))
